/** @jsxImportSource theme-ui */
//@ts-nocheck

import Head from 'next/head';
import { Box, Container, Flex, Button } from 'krado-react';
import Heading from '@/components/fixed-krado-components/Heading';
import Text from '@/components/fixed-krado-components/Text';
import Image from 'next/image';

export default function Home() {
  return (
    <>
      <Head>
        <title>Set Theory</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Flex
        as='main'
        sx={{
          minHeight: '100vh',
          height: '100%',
          width: '100%',
          flexDirection: 'column'
        }}
      >
        <Flex sx={{ width: '100%' }}>
          <Image
            src='/logo.svg'
            alt='Set Theory Logo'
            sx={{ width: '125px', height: '125px' }}
            width={100}
            height={100}
            priority
          />
        </Flex>
        <Container
          as='main'
          sx={{
            marginY: 'auto',
            display: 'flex',
            flexDirection: 'column',
            justifyContent: 'center',
            alignItems: 'center',
            width: '100%',
            height: '100%'
          }}
        >
          <Flex
            sx={{
              flexDirection: 'column',
              textAlign: 'center',
              marginBottom: [4, 5],
              gap: 3
            }}
          >
            <Heading
              as='h1'
              sx={{
                fontSize: ['48px', '100px', '109px', '150px'],
                lineHeight: '1.1',
                fontWeight: 'bold',
                fontStretch: '125%'
              }}
            >
              SET THEORY
            </Heading>
            <Text as='p' variant='body.summary'>
              A company specializing in design and technology that explores the
              theory behind the creative process to inspire others.
            </Text>
          </Flex>

          <a
            href='https://podcast.imsety.com/'
            target='_blank'
            rel='noindex nofollow'
          >
            <Button>Listen to podcast</Button>
          </a>
        </Container>
      </Flex>
    </>
  );
}
